### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by r3dt3am** [EnginDemirbilek/NorthStarC2#1]
Hi !!

Congratulations on the great job. I have deployed Northstar on a Ubuntu Bionic with Mysql. While other functionalities are working as expected, upload feature does not work. After browsing the file does not get selected and upload also does not happen. Is this a common problem or some problem at my end only ?
Do you have plans to further increase the functionality ?

**Comment by EnginDemirbilek** [comment]
Hi, thank you for first issue ! Its a common issue that file name is not shown when you select file. But you should be able to upload file when you click upload button after selecting it. I would recommend that make sure that /sfiles/ and /files/ directories are belongs to www-data:www-data user. But in case for any other problem, i will check it out now. Untill it gets fixed you can use download command to upload files to clients. Syntax: download http://externalurl/filename

**Comment by EnginDemirbilek** [comment]
Hi I've fixed the issues. Now you can see the filename as you select file and also i've checked that upload function is working properly.  Thanks for helping us to improve NorthStar.
