### ISSUE TITLE
install northstarc2 in internet environment

### ISSUE THREAD

**Issue by kake123qw** [EnginDemirbilek/NorthStarC2#2]
Hello.
I want to install northstarc2 on internet environment. it means that i want use it on Ubuntu server VPS with public IP address instead of 127.0.0.1 local host. please guide me how to implement this issue.
thanks.

**Comment by EnginDemirbilek** [comment]
Hi thank for your review,

You can directly use NorthStar on VPS. You can access web panel via browsing your public ip adress. http://PUBLICIP.com

**Comment by kake123qw** [comment]
you mentioned that http://127.0.0.1/getin.php --> iwant to know, how can i type? for example my ip is 10.10.5.8. . the final url for logging in to panel is http://10.10.5.8.com/getin.php ???

**Comment by hekindmn** [comment]
Yes, that is also true for public IP as well.
