### ISSUE TITLE
payload

### ISSUE THREAD

**Issue by mikehussygr9** [EnginDemirbilek/NorthStarC2#3]
Nothing mentioned about payload generation

**Comment by hekindmn** [comment]
Hi,
You can build the stager from the source code, it is explained here : 
https://github.com/EnginDemirbilek/NorthStarC2/wiki/NorthStar-Stager-%7C-Commands

If you're asking about msfvenom equivalent-like payloads (rev http, rev tcp and so on) or in different languages, only .NET is supported at the moment and NorthStar Stager  only communicates to the C2 server via HTTP requests, which is explained here : 
https://github.com/EnginDemirbilek/NorthStarC2/wiki/Architecture

We're currently developing different types of payloads and connection architectures.
Let us know if you have any further questions
