### ISSUE TITLE
Unable to connect client

### ISSUE THREAD

**Issue by merlin123h** [EnginDemirbilek/NorthStarC2#4]
Hi. 
I am using the NorthStar web based C2 framework. unfortunately, after executing my .exe file on my ubuntu server, the output .exe file runs silently. But it not shown in session tab. In "session logs" tab the Log Content column value is "Error; update details". please guide me how solve this problem. the details of this problem is shown in attached picture.
thanks
![yy](https://user-images.githubusercontent.com/67941449/101292179-bf717900-37c2-11eb-8fa0-bafa2f00b655.PNG)

**Comment by hekindmn** [comment]
NorthStar Stager is an application written in .NET so it wont work with default ubuntu server installations. This C2 is designed and supported for Windows use only, at the moment.

Have a nice day !
